# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    curl https://sh.rustup.rs -sSf | sh
    rustc --version
    cargo --version
  displayName: 'Install Rust'

- script: |
    cargo test
  displayName: 'Run unit tests'
