[package]
name = "pactical"
version = "0.1.0"
authors = ["David Mitchell <monch1962@gmail.com>"]

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_derive = "1.0"
handlebars = "2.0.2"
chrono = "0.4.9"
Inflector = "0.11.4"